import turtle
import random
turtle.colormode(255)
turtle.speed(0)
turtle.seth(45)
turtle.begin_fill()
for i in range(50):
    h = random.randint(0, 360)
    turtle.seth(h)
    x = random.randint(-400, 400)
    y = random.randint(-600, 600)
    turtle.penup()
    turtle.goto(x,y)
    turtle.pendown()
    r = random.randint(0,255)
    g = random.randint(0, 255)
    b = random.randint(0, 255)
    turtle.color(r, g, b)
    a = random.randint(20,50)
    turtle.begin_fill()
    turtle.fd(a)
    turtle.circle(a/2,180)
    turtle.rt(90)
    turtle.circle(a/2,180)
    turtle.fd(a)
    turtle.end_fill()
turtle.color(random.randint(0,255), random.randint(0,255), random.randint(0,255))
turtle.penup()
turtle.goto(0,0)
turtle.pendown()
turtle.write('教师节快乐!', align= 'center', font= ('华文楷体', 80))
turtle.penup()
turtle.goto(200,-100)
turtle.pendown()
turtle.write('刘相瑜敬上', align='right', font=('华文楷体', 40))
turtle.ht()
turtle.done()