import turtle
turtle.color('yellow')
turtle.begin_fill()
turtle.circle(100)
turtle.end_fill()
turtle.penup()
turtle.goto(-50,50)
turtle.color('white')
turtle.pendown()
turtle.begin_fill()
for i in range(4):
    turtle.forward(100)
    turtle.left(90)
turtle.end_fill()
turtle.done()